# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Generator

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Copy scripts and Checkout gh-pages
      run: |
        ls -lah
        mkdir ../temp
        cp src/* ../temp
        
        # Check if branch exists
        if ! git fetch --no-tags --depth=1 origin gh-pages; then
          # Create new branch if not exists
          echo "Creating branch"
          git switch --orphan gh-pages
        
        else
          # Checkout remote branch if exists
          echo "Checking out remote branch"
          git switch gh-pages
        
        fi
        
        ls -lah
        ls -lah ..
        ls -lah ../temp
    
    - uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        set -xe
        python -VV
        python -m pip install beautifulsoup4 cssutils requests
    
    - name: Run Generator
      run: |
        mkdir src
        cp ../temp/* src/
        pushd src
        ls -lah
        python github_actions.py "../"
        popd
        rm -rf src/
    
    - name: Zotero Download
      env:
        ZOTERO: ${{ secrets.ZOTERO_USERID }}
      if: "${{ env.ZOTERO != '' }}"
      run: |
        rm -rf zotero.json
        curl -L "https://api.zotero.org/users/${ZOTERO}/publications/items?linkwrap=1&order=date&sort=desc&start=0&include=data&limit=100" --output zotero.json
        ls -lah
        
    - name: Profile Readme Download
      env:
        REPO_NAME: ${{ github.event.repository.name }}
      run: |
        echo "$REPO_NAME"
        USER=$(python -c "print('${REPO_NAME}'.split('/')[0])")
        echo "$USER"
        rm -rf profile-readme.md
        if ! curl -L "https://raw.githubusercontent.com/${USER}/${USER}/main/README.md" --output profile-readme.md; then
          echo "Failed to download readme."
        fi
        ls -lah
        
    - uses: EndBug/add-and-commit@v7
      with:
        # Determines the way the action fills missing author name and email. Three options are available:
        # - github_actor -> UserName <UserName@users.noreply.github.com>
        # - user_info -> Your Display Name <your-actual@email.com>
        # - github_actions -> github-actions <email associated with the github logo>
        # Default: github_actor
        default_author: github_actions
        
        branch: gh-pages
        branch_mode: create

        # The message for the commit.
        # Default: 'Commit from GitHub Actions (name of the workflow)'
        message: '[U] Update channel content'
