# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Generator

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        set -xe
        python -VV
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run Generator
      run: |
        pushd src
        python github_actions.py
        popd
    
    - uses: EndBug/add-and-commit@v7
      with:
        # Determines the way the action fills missing author name and email. Three options are available:
        # - github_actor -> UserName <UserName@users.noreply.github.com>
        # - user_info -> Your Display Name <your-actual@email.com>
        # - github_actions -> github-actions <email associated with the github logo>
        # Default: github_actor
        default_author: github_actions

        # The message for the commit.
        # Default: 'Commit from GitHub Actions (name of the workflow)'
        message: '[U] Generate json'
